name: Scheduled Workflow

on:
  schedule:
    - cron: '5 * * * *'  # Run once every hour (at the beginning of the hour)

jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
    - name: Print a message
      run: echo "This workflow is running on a schedule."
