name: Run and Save JavaScript Results

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  run_and_save_results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: json

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run script and save results
        run: node script.js > data.json
        working-directory: ''

      - name: Commit and push the updated data.json
        run: |
          git config user.name "kacollins"
          git config user.email "kimberlyacollins@gmail.com"
          git add data.json
          git commit -m "Update data.json from script.js"
          git push origin json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
