name: Scheduled Workflow

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
    - name: Print a message
      run: echo "This workflow is running on a schedule."
